name: Android CI

on:
  push:
  pull_request:
    paths-ignore:
      - 'src/**'
      - 'ios/**'
      - '__tests__/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install npm dependencies
        run: yarn install
      - name: Parse Git short hash
        run: echo "git_short_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Get OrangeHRM version from package.json
        run: echo "orangehrm_version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: Update package.json version
        run: yarn version --no-git-tag-version --new-version ${{ env.orangehrm_version }}-${{ env.git_short_hash }}
      - name: Update Android project version
        run: node scripts/sync-version.js --debug
      - name: Build with Gradle
        run: cd android && ./gradlew assembleRelease
      - name: Upload Artifacts(arm64-v8a-release.apk)
        uses: actions/upload-artifact@v2
        with:
          name: orangehrm(${{ env.git_short_hash }})-arm64-v8a
          path: android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
      - name: Upload Artifacts(armeabi-v7a-release.apk)
        uses: actions/upload-artifact@v2
        with:
          name: orangehrm(${{ env.git_short_hash }})-armeabi-v7a
          path: android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
      - name: Upload Artifacts(x86_64-release.apk)
        uses: actions/upload-artifact@v2
        with:
          name: orangehrm(${{ env.git_short_hash }})-x86_64
          path: android/app/build/outputs/apk/release/app-x86_64-release.apk
      - name: Upload Artifacts(x86-release.apk)
        uses: actions/upload-artifact@v2
        with:
          name: orangehrm(${{ env.git_short_hash }})-x86
          path: android/app/build/outputs/apk/release/app-x86-release.apk
      - name: Upload Artifacts(universal-release.apk)
        uses: actions/upload-artifact@v2
        with:
          name: orangehrm(${{ env.git_short_hash }})-universal
          path: android/app/build/outputs/apk/release/app-universal-release.apk
